package model;

/**
 * Defines a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key
 * (either as a header, a cookie parameter or as a query parameter), OAuth2's common flows (implicit, password,
 * client credentials and authorization code) as defined in RFC6749, and OpenID Connect Discovery.
 */
public class SecurityScheme {
    /**
     * REQUIRED. The type of the security scheme. Valid values are "apiKey", "http", "oauth2", "openIdConnect".
     */
    private String type;

    /**
     * 	A short description for security scheme. CommonMark syntax MAY be used for rich text representation.
     */
    private String description;

    /**
     * REQUIRED. The name of the header, query or cookie parameter to be used.
     */
    private String name;

    /**
     * REQUIRED. The location of the API key. Valid values are "query", "header" or "cookie".
     */
    private String in;

    /**
     * REQUIRED. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235.
     * The values used SHOULD be registered in the IANA Authentication Scheme registry.
     */
    private String scheme;

    /**
     * A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an
     * authorization server, so this information is primarily for documentation purposes.
     */
    private String bearerFormat;

    /**
     * REQUIRED. An object containing configuration information for the flow types supported.
     */
    private OAuthFlows flows;

    /**
     * REQUIRED. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of a URL.
     */
    private String openIdConnectUrl;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIn() {
        return in;
    }

    public void setIn(String in) {
        this.in = in;
    }

    public String getScheme() {
        return scheme;
    }

    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    public String getBearerFormat() {
        return bearerFormat;
    }

    public void setBearerFormat(String bearerFormat) {
        this.bearerFormat = bearerFormat;
    }

    public OAuthFlows getFlows() {
        return flows;
    }

    public void setFlows(OAuthFlows flows) {
        this.flows = flows;
    }

    public String getOpenIdConnectUrl() {
        return openIdConnectUrl;
    }

    public void setOpenIdConnectUrl(String openIdConnectUrl) {
        this.openIdConnectUrl = openIdConnectUrl;
    }
}
